# Generated by Django 4.0.2 on 2022-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('elec', models.CharField(default='', max_length=100)),
                ('waterconsp', models.CharField(default='', max_length=100)),
                ('meterread', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
