# Generated by Django 4.0.2 on 2022-02-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='elec',
            new_name='elect_consumption',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='name',
            new_name='name_of_card',
        ),
    ]
