# Generated by Django 4.0.2 on 2022-02-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0002_rename_elec_reading_elect_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='name_of_card',
            new_name='name_of_project',
        ),
    ]
